package com.gravityrd.receng.web.webshop.jsondto;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize.Inclusion;

/**
 * The list of items recommended to a user.
 * @see com.gravityrd.recenginterface.webshop.ItemRecommendation
 */
public class GravityItemRecommendation {

	/**
	 * The recommendationId is generated by the recommendation engine.  See {@link GravityEvent#recommendationId }.
	 */
	public String recommendationId;

	/**
	 * The list of items. This is populated only if the scenario specifies to do so, otherwise this is null.
	 * The items in this list only have the NameValues specified by the scenario.
	 * The list of NameValues specified by the scenario can be overridden by the {@link GravityRecommendationContext#resultNameValues } on a per request basis.
	 */
	public GravityItem[] items;

	/**
	 * The identifiers of the recommended items.
	 */
	public String[] itemIds;

	public double[] predictionValues;

	@JsonSerialize(include = Inclusion.NON_NULL)
	public GravityNameValue[] outputNameValues;
}
