package com.gravityrd.receng.web.webshop.jsondto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.gravityrd.receng.web.webshop.jsondto.facet.FacetResponse;

import java.util.Arrays;
import java.util.Collection;
import java.util.Map;

/**
 * The list of items recommended to a user.
 */
public class GravityItemRecommendation {

	/**
	 * The recommendationId is generated by the recommendation engine.  See {@link GravityEvent#recommendationId }.
	 */
	public String recommendationId;

	/**
	 * The list of items. This is populated only if the scenario specifies to do so, otherwise this is null.
	 * The items in this list only have the NameValues specified by the scenario.
	 * The list of NameValues specified by the scenario can be overridden by the {@link GravityRecommendationContext#resultNameValues } on a per request basis.
	 */
	public GravityItem[] items;

	/**
	 * The identifiers of the recommended items.
	 */
	public String[] itemIds;

	public double[] predictionValues;

	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public GravityNameValue[] outputNameValues;

	@Override
	public String toString() {
		final StringBuilder sb = new StringBuilder("GravityItemRecommendation{");
		sb.append("recommendationId='").append(recommendationId).append('\'');
		sb.append(", items=").append(Arrays.toString(items));
		sb.append(", itemIds=").append(Arrays.toString(itemIds));
		sb.append(", predictionValues=").append(Arrays.toString(predictionValues));
		sb.append(", outputNameValues=").append(Arrays.toString(outputNameValues));
		sb.append('}');
		return sb.toString();
	}

	public Map<String, FacetResponse> facets;
	
	public Long totalResults;
	
	public Long took;

}
